version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
